name: tddns Development CI

on:
  push:
    branches:
      - "main"
      - "release/*"
  pull_request:
    branches:
      - "main"
      - "release/*"

jobs:
  build-binary:
    name: Build Development Binary
    runs-on: ubuntu-latest
    container:
      image: debian:trixie-slim@sha256:3a39a0592364683e6bab97937b72cad5a8fa6dcbbee90edb3bb48c7f8e94f258
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Update repositories
        run: apt-get update
      - name: Install dependencies
        run: apt-get install --no-install-recommends -y gcc libc6-dev libcurl4-openssl-dev make pkg-config
      - name: Build binary
        run: make tddns

  build-container:
    name: Build Runtime Container
    runs-on: ubuntu-latest
    steps:
      - name: Prepare metadata
        id: meta
        run: |
          echo "PUSH=${{ github.ref == 'refs/heads/main' }}" >>$GITHUB_OUTPUT
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "SHORT_SHA=$SHORT_SHA" >>$GITHUB_OUTPUT
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "TAGS=${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:latest,${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:$SHORT_SHA" >>$GITHUB_OUTPUT
          else
            echo "TAGS=${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:latest" >>$GITHUB_OUTPUT
          fi
      - name: Run actions/checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Run docker/setup-buildx-action
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4
      - name: Run docker/login-action
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get build date
        id: build_date
        run: echo "date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >>"${GITHUB_OUTPUT}"
      - name: Build Container
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          context: .
          file: ./Dockerfile
          push: ${{ steps.meta.outputs.PUSH }}
          load: true
          tags: ${{ steps.meta.outputs.TAGS }}
          build-args: |
            VERSION=${{ github.sha }}
            COMMIT_SHA=${{ github.sha }}
            BUILD_DATE=${{ steps.build_date.outputs.date }}
