name: tddns Development CI

on:
  push:
    branches:
      - "main"
      - "release/*"
  pull_request:
    branches:
      - "main"
      - "release/*"

jobs:
  build-binary:
    name: Build Development Binary
    runs-on: ubuntu-latest
    container:
      image: debian:trixie-slim@sha256:d7e12182ce18b85b93007c1dedf31f2d29e01ccf3182cc4017c709b6259bc132
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Update repositories
        run: apt-get update
      - name: Install dependencies
        run: apt-get install --no-install-recommends -y gcc libc6-dev libcurl4-openssl-dev make pkg-config
      - name: Build binary
        run: make tddns

  build-container:
    name: Build Runtime Container
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Prepare metadata
        id: meta
        run: |
          image="$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')"
          tags="${image}:latest"
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            tags="${tags},${image}:$(echo "${GITHUB_SHA}" | cut -c1-7)"
          fi
          {
            echo "PUSH=${{ github.ref == 'refs/heads/main' }}"
            echo "IMAGE=${image}"
            echo "TAGS=${tags}"
          } >>"$GITHUB_OUTPUT"
      - name: Run docker/setup-buildx-action
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4
      - name: Run docker/login-action
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get build date
        id: build_date
        run: echo "date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >>"${GITHUB_OUTPUT}"
      - name: Build Container
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          context: .
          file: ./Dockerfile
          push: ${{ steps.meta.outputs.PUSH }}
          load: true
          tags: ${{ steps.meta.outputs.TAGS }}
          build-args: |
            VERSION=${{ github.sha }}
            COMMIT_SHA=${{ github.sha }}
            BUILD_DATE=${{ steps.build_date.outputs.date }}
