name: Security Analysis

on:
  push:
    branches:
      - "main"
      - "release/*"
  pull_request:
    branches:
      - "main"
      - "release/*"
  schedule:
    - cron: "23 3 * * *" # Daily at 03:23 UTC

jobs:
  analyze:
    name: CodeQL
    runs-on: ubuntu-latest
    container:
      image: debian:trixie-slim@sha256:a99cfc517144bc59b1978475ec53b46ecabec7e43635402ee5b77cc54cd1b20a
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Run actions/checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Update repositories
        run: apt-get update
      - name: Install dependencies
        run: apt-get install --no-install-recommends -y gcc libc6-dev libcurl4-openssl-dev make pkg-config
      - name: Run github/codeql-action/init
        uses: github/codeql-action/init@1c5b675653bb5c22dbe9b12b556ec555138e09fd # v4
        with:
          languages: c-cpp
          build-mode: manual
          queries: security-and-quality
      - name: Build
        env:
          CC: gcc
        run: make clean all
      - name: Run github/codeql-action/analyze
        uses: github/codeql-action/analyze@1c5b675653bb5c22dbe9b12b556ec555138e09fd # v4
        with:
          category: "/language:c"
