name: Security Analysis

on:
  push:
    branches:
      - "main"
      - "release/*"
  pull_request:
    branches:
      - "main"
      - "release/*"
  schedule:
    - cron: "23 3 * * *" # Daily at 03:23 UTC

jobs:
  analyze:
    name: CodeQL
    runs-on: ubuntu-latest
    container:
      image: debian:trixie-slim@sha256:28de0877c2189802884ccd20f15ee41c203573bd87bb6b883f5f46362d24c5c2
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Run actions/checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Update repositories
        run: apt-get update
      - name: Install dependencies
        run: apt-get install --no-install-recommends -y gcc libc6-dev libcurl4-openssl-dev make pkg-config
      - name: Run github/codeql-action/init
        uses: github/codeql-action/init@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4
        with:
          languages: c-cpp
          build-mode: manual
          queries: security-and-quality
      - name: Build
        env:
          CC: gcc
        run: make clean all
      - name: Run github/codeql-action/analyze
        uses: github/codeql-action/analyze@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4
        with:
          category: "/language:c"
