name: Security Analysis

on:
  push:
    branches:
      - "main"
      - "release/*"
  pull_request:
    branches:
      - "main"
      - "release/*"
  schedule:
    - cron: "23 3 * * *" # Daily at 03:23 UTC

jobs:
  analyze:
    name: CodeQL
    runs-on: ubuntu-latest
    container:
      image: debian:trixie-slim@sha256:020c0d20b9880058cbe785a9db107156c3c75c2ac944a6aa7ab59f2add76a7bd
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Run actions/checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Update repositories
        run: apt-get update
      - name: Install dependencies
        run: apt-get install --no-install-recommends -y gcc libc6-dev libcurl4-openssl-dev make pkg-config
      - name: Run github/codeql-action/init
        uses: github/codeql-action/init@e0647621c2984b5ed2f768cb892365bf2a616ad1 # v4
        with:
          languages: c-cpp
          build-mode: manual
          queries: security-and-quality
      - name: Build
        env:
          CC: gcc
        run: make clean all
      - name: Run github/codeql-action/analyze
        uses: github/codeql-action/analyze@e0647621c2984b5ed2f768cb892365bf2a616ad1 # v4
        with:
          category: "/language:c"
